name: transmon-gpu
channels:
  - conda-forge
  - nvidia
dependencies:
  - python==3.10
  - cudatoolkit=11.2.2
  - pip:
      - numpy==1.26.0
      - matplotlib==3.8.0
      - imageio==2.31.5
      - scqubits==3.2.0
      - tensorflow==2.9
